import type { Problem } from "@repo/shared";

const NEETCODE_150_SLUGS: Record<number, string> = {
  1: "two-integer-sum",
  2: "add-two-numbers",
  3: "longest-substring-without-duplicates",
  4: "median-of-two-sorted-arrays",
  5: "longest-palindromic-substring",
  7: "reverse-integer",
  10: "regular-expression-matching",
  11: "max-water-container",
  15: "three-integer-sum",
  17: "combinations-of-a-phone-number",
  19: "remove-node-from-end-of-linked-list",
  20: "validate-parentheses",
  21: "merge-two-sorted-linked-lists",
  22: "generate-parentheses",
  23: "merge-k-sorted-linked-lists",
  25: "reverse-nodes-in-k-group",
  33: "find-target-in-rotated-sorted-array",
  36: "valid-sudoku",
  39: "combination-target-sum",
  40: "combination-target-sum-ii",
  42: "trapping-rain-water",
  43: "multiply-strings",
  45: "jump-game-ii",
  46: "permutations",
  48: "rotate-matrix",
  49: "anagram-groups",
  50: "pow-x-n",
  51: "n-queens",
  53: "maximum-subarray",
  54: "spiral-matrix",
  55: "jump-game",
  56: "merge-intervals",
  57: "insert-new-interval",
  62: "count-paths",
  66: "plus-one",
  70: "climbing-stairs",
  72: "edit-distance",
  73: "set-zeroes-in-matrix",
  74: "search-2d-matrix",
  76: "minimum-window-with-characters",
  78: "subsets",
  79: "search-for-word",
  84: "largest-rectangle-in-histogram",
  90: "subsets-ii",
  91: "decode-ways",
  97: "interleaving-string",
  98: "valid-binary-search-tree",
  100: "same-binary-tree",
  102: "level-order-traversal-of-binary-tree",
  104: "depth-of-binary-tree",
  105: "binary-tree-from-preorder-and-inorder-traversal",
  110: "balanced-binary-tree",
  115: "count-subsequences",
  121: "buy-and-sell-crypto",
  124: "binary-tree-maximum-path-sum",
  125: "is-palindrome",
  127: "word-ladder",
  128: "longest-consecutive-sequence",
  130: "surrounded-regions",
  131: "palindrome-partitioning",
  133: "clone-graph",
  134: "gas-station",
  136: "single-number",
  138: "copy-linked-list-with-random-pointer",
  139: "word-break",
  141: "linked-list-cycle-detection",
  143: "reorder-linked-list",
  146: "lru-cache",
  150: "evaluate-reverse-polish-notation",
  152: "maximum-product-subarray",
  153: "find-minimum-in-rotated-sorted-array",
  155: "minimum-stack",
  167: "two-integer-sum-ii",
  190: "reverse-bits",
  191: "number-of-one-bits",
  198: "house-robber",
  199: "binary-tree-right-side-view",
  200: "count-number-of-islands",
  202: "non-cyclical-number",
  206: "reverse-a-linked-list",
  207: "course-schedule",
  208: "implement-prefix-tree",
  210: "course-schedule-ii",
  211: "design-word-search-data-structure",
  212: "search-for-word-ii",
  213: "house-robber-ii",
  215: "kth-largest-element-in-an-array",
  217: "duplicate-integer",
  226: "invert-a-binary-tree",
  230: "kth-smallest-integer-in-bst",
  235: "lowest-common-ancestor-in-binary-search-tree",
  238: "products-of-array-discluding-self",
  239: "sliding-window-maximum",
  242: "is-anagram",
  252: "meeting-schedule",
  253: "meeting-schedule-ii",
  261: "valid-tree",
  268: "missing-number",
  269: "foreign-dictionary",
  271: "string-encode-and-decode",
  286: "islands-and-treasure",
  287: "find-duplicate-integer",
  295: "find-median-in-a-data-stream",
  297: "serialize-and-deserialize-binary-tree",
  300: "longest-increasing-subsequence",
  309: "buy-and-sell-crypto-with-cooldown",
  312: "burst-balloons",
  322: "coin-change",
  323: "count-connected-components",
  329: "longest-increasing-path-in-matrix",
  332: "reconstruct-flight-path",
  338: "counting-bits",
  347: "top-k-elements-in-list",
  355: "design-twitter-feed",
  371: "sum-of-two-integers",
  416: "partition-equal-subset-sum",
  417: "pacific-atlantic-water-flow",
  424: "longest-repeating-substring-with-replacement",
  435: "non-overlapping-intervals",
  494: "target-sum",
  518: "coin-change-ii",
  543: "binary-tree-diameter",
  567: "permutation-string",
  572: "subtree-of-a-binary-tree",
  621: "task-scheduling",
  647: "palindromic-substrings",
  678: "valid-parenthesis-string",
  684: "redundant-connection",
  695: "max-area-of-island",
  703: "kth-largest-integer-in-a-stream",
  704: "binary-search",
  739: "daily-temperatures",
  743: "network-delay-time",
  746: "min-cost-climbing-stairs",
  763: "partition-labels",
  778: "swim-in-rising-water",
  787: "cheapest-flight-path",
  846: "hand-of-straights",
  853: "car-fleet",
  875: "eating-bananas",
  973: "k-closest-points-to-origin",
  981: "time-based-key-value-store",
  994: "rotting-fruit",
  1046: "last-stone-weight",
  1143: "longest-common-subsequence",
  1448: "count-good-nodes-in-binary-tree",
  1584: "min-cost-to-connect-points",
  1851: "minimum-interval-including-query",
  1899: "merge-triplets-to-form-target",
  2013: "count-squares",
};

export function getProblemQuestionUrl(problem: Pick<Problem, "leetcodeId" | "url">) {
  const storedNeetcodeSlug = extractNeetcodeProblemSlug(problem.url);
  if (storedNeetcodeSlug) return buildNeetcodeQuestionUrl(storedNeetcodeSlug);

  const mappedSlug = problem.leetcodeId ? NEETCODE_150_SLUGS[problem.leetcodeId] : undefined;
  return mappedSlug ? buildNeetcodeQuestionUrl(mappedSlug) : problem.url;
}

function buildNeetcodeQuestionUrl(slug: string) {
  return `https://neetcode.io/problems/${slug}/question?list=neetcode150`;
}

function extractNeetcodeProblemSlug(url: string) {
  try {
    const parsed = new URL(url);
    if (!parsed.hostname.endsWith("neetcode.io")) return null;
    return parsed.pathname.match(/^\/problems\/([^/]+)/)?.[1] ?? null;
  } catch {
    return null;
  }
}
